package com.jimi.smt.eps_server.entity;

public class CenterLogin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_login.id
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_login.line
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    private Integer line;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_login.mac
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    private String mac;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_login.ip
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_login.port
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    private Integer port;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_login.id
     *
     * @return the value of center_login.id
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_login.id
     *
     * @param id the value for center_login.id
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_login.line
     *
     * @return the value of center_login.line
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public Integer getLine() {
        return line;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_login.line
     *
     * @param line the value for center_login.line
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public void setLine(Integer line) {
        this.line = line;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_login.mac
     *
     * @return the value of center_login.mac
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_login.mac
     *
     * @param mac the value for center_login.mac
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public void setMac(String mac) {
        this.mac = mac == null ? null : mac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_login.ip
     *
     * @return the value of center_login.ip
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_login.ip
     *
     * @param ip the value for center_login.ip
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_login.port
     *
     * @return the value of center_login.port
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_login.port
     *
     * @param port the value for center_login.port
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public void setPort(Integer port) {
        this.port = port;
    }
}