package com.jimi.smt.eps_server.entity;

public class Display {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column display.line
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    private Integer line;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column display.work_order
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    private String workOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column display.board_type
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    private Integer boardType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column display.line
     *
     * @return the value of display.line
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public Integer getLine() {
        return line;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column display.line
     *
     * @param line the value for display.line
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public void setLine(Integer line) {
        this.line = line;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column display.work_order
     *
     * @return the value of display.work_order
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public String getWorkOrder() {
        return workOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column display.work_order
     *
     * @param workOrder the value for display.work_order
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public void setWorkOrder(String workOrder) {
        this.workOrder = workOrder == null ? null : workOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column display.board_type
     *
     * @return the value of display.board_type
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public Integer getBoardType() {
        return boardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column display.board_type
     *
     * @param boardType the value for display.board_type
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public void setBoardType(Integer boardType) {
        this.boardType = boardType;
    }
}