package com.jimi.smt.eps_server.entity;

import java.util.Date;

public class Operation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.id
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.operator
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.time
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.type
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.result
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.lineseat
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    private String lineseat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.material_no
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    private String materialNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.old_material_no
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    private String oldMaterialNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.line
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    private Integer line;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.scanlineseat
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    private String scanlineseat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.remark
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.program_id
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    private String programId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.work_order
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    private String workOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.board_type
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    private Integer boardType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.id
     *
     * @return the value of operation.id
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.id
     *
     * @param id the value for operation.id
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.operator
     *
     * @return the value of operation.operator
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.operator
     *
     * @param operator the value for operation.operator
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.time
     *
     * @return the value of operation.time
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.time
     *
     * @param time the value for operation.time
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.type
     *
     * @return the value of operation.type
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.type
     *
     * @param type the value for operation.type
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.result
     *
     * @return the value of operation.result
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.result
     *
     * @param result the value for operation.result
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.lineseat
     *
     * @return the value of operation.lineseat
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public String getLineseat() {
        return lineseat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.lineseat
     *
     * @param lineseat the value for operation.lineseat
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public void setLineseat(String lineseat) {
        this.lineseat = lineseat == null ? null : lineseat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.material_no
     *
     * @return the value of operation.material_no
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public String getMaterialNo() {
        return materialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.material_no
     *
     * @param materialNo the value for operation.material_no
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public void setMaterialNo(String materialNo) {
        this.materialNo = materialNo == null ? null : materialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.old_material_no
     *
     * @return the value of operation.old_material_no
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public String getOldMaterialNo() {
        return oldMaterialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.old_material_no
     *
     * @param oldMaterialNo the value for operation.old_material_no
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public void setOldMaterialNo(String oldMaterialNo) {
        this.oldMaterialNo = oldMaterialNo == null ? null : oldMaterialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.line
     *
     * @return the value of operation.line
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public Integer getLine() {
        return line;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.line
     *
     * @param line the value for operation.line
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public void setLine(Integer line) {
        this.line = line;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.scanlineseat
     *
     * @return the value of operation.scanlineseat
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public String getScanlineseat() {
        return scanlineseat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.scanlineseat
     *
     * @param scanlineseat the value for operation.scanlineseat
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public void setScanlineseat(String scanlineseat) {
        this.scanlineseat = scanlineseat == null ? null : scanlineseat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.remark
     *
     * @return the value of operation.remark
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.remark
     *
     * @param remark the value for operation.remark
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.program_id
     *
     * @return the value of operation.program_id
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public String getProgramId() {
        return programId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.program_id
     *
     * @param programId the value for operation.program_id
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public void setProgramId(String programId) {
        this.programId = programId == null ? null : programId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.work_order
     *
     * @return the value of operation.work_order
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public String getWorkOrder() {
        return workOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.work_order
     *
     * @param workOrder the value for operation.work_order
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public void setWorkOrder(String workOrder) {
        this.workOrder = workOrder == null ? null : workOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.board_type
     *
     * @return the value of operation.board_type
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public Integer getBoardType() {
        return boardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.board_type
     *
     * @param boardType the value for operation.board_type
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    public void setBoardType(Integer boardType) {
        this.boardType = boardType;
    }
}