package com.jimi.smt.eps_server.mapper;

import com.jimi.smt.eps_server.entity.CenterLogin;
import com.jimi.smt.eps_server.entity.CenterLoginExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CenterLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_login
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    long countByExample(CenterLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_login
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    int deleteByExample(CenterLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_login
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_login
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    int insert(CenterLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_login
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    int insertSelective(CenterLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_login
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    List<CenterLogin> selectByExample(CenterLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_login
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    CenterLogin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_login
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    int updateByExampleSelective(@Param("record") CenterLogin record, @Param("example") CenterLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_login
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    int updateByExample(@Param("record") CenterLogin record, @Param("example") CenterLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_login
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    int updateByPrimaryKeySelective(CenterLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_login
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    int updateByPrimaryKey(CenterLogin record);
}