package com.jimi.smt.eps_server.mapper;

import com.jimi.smt.eps_server.entity.CenterState;
import com.jimi.smt.eps_server.entity.CenterStateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CenterStateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_state
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    long countByExample(CenterStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_state
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    int deleteByExample(CenterStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_state
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    int deleteByPrimaryKey(Integer line);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_state
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    int insert(CenterState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_state
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    int insertSelective(CenterState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_state
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    List<CenterState> selectByExample(CenterStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_state
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    CenterState selectByPrimaryKey(Integer line);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_state
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    int updateByExampleSelective(@Param("record") CenterState record, @Param("example") CenterStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_state
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    int updateByExample(@Param("record") CenterState record, @Param("example") CenterStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_state
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    int updateByPrimaryKeySelective(CenterState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_state
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    int updateByPrimaryKey(CenterState record);
}