package com.jimi.smt.eps_server.mapper;

import com.jimi.smt.eps_server.entity.Display;
import com.jimi.smt.eps_server.entity.DisplayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DisplayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table display
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    long countByExample(DisplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table display
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    int deleteByExample(DisplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table display
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    int deleteByPrimaryKey(Integer line);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table display
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    int insert(Display record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table display
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    int insertSelective(Display record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table display
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    List<Display> selectByExample(DisplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table display
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    Display selectByPrimaryKey(Integer line);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table display
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    int updateByExampleSelective(@Param("record") Display record, @Param("example") DisplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table display
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    int updateByExample(@Param("record") Display record, @Param("example") DisplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table display
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    int updateByPrimaryKeySelective(Display record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table display
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    int updateByPrimaryKey(Display record);
}