package com.jimi.smt.eps_server.mapper;

import com.jimi.smt.eps_server.entity.Operation;
import com.jimi.smt.eps_server.entity.OperationDetials;
import com.jimi.smt.eps_server.entity.OperationExample;
import com.jimi.smt.eps_server.entity.bo.ReportParameter;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OperationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    int countByExample(OperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    int deleteByExample(OperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    int insert(Operation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    int insertSelective(Operation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    List<Operation> selectByExample(OperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    Operation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    int updateByExampleSelective(@Param("record") Operation record, @Param("example") OperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    int updateByExample(@Param("record") Operation record, @Param("example") OperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    int updateByPrimaryKeySelective(Operation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated Tue Sep 18 17:12:42 CST 2018
     */
    int updateByPrimaryKey(Operation record);
    
    List<OperationDetials> selectByClientParameter(ReportParameter record);
    
    int countByClientParameter(ReportParameter record);
    
    List<OperationDetials> selectByOperationParameter(ReportParameter record);
    
    int countByOperationParameter(ReportParameter record);
}