package com.jimi.smt.eps_server.mapper;

import com.jimi.smt.eps_server.entity.SocketLog;
import com.jimi.smt.eps_server.entity.SocketLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SocketLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_log
     *
     * @mbg.generated Fri Aug 24 09:38:43 CST 2018
     */
    long countByExample(SocketLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_log
     *
     * @mbg.generated Fri Aug 24 09:38:43 CST 2018
     */
    int deleteByExample(SocketLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_log
     *
     * @mbg.generated Fri Aug 24 09:38:43 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_log
     *
     * @mbg.generated Fri Aug 24 09:38:43 CST 2018
     */
    int insert(SocketLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_log
     *
     * @mbg.generated Fri Aug 24 09:38:43 CST 2018
     */
    int insertSelective(SocketLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_log
     *
     * @mbg.generated Fri Aug 24 09:38:43 CST 2018
     */
    List<SocketLog> selectByExample(SocketLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_log
     *
     * @mbg.generated Fri Aug 24 09:38:43 CST 2018
     */
    SocketLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_log
     *
     * @mbg.generated Fri Aug 24 09:38:43 CST 2018
     */
    int updateByExampleSelective(@Param("record") SocketLog record, @Param("example") SocketLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_log
     *
     * @mbg.generated Fri Aug 24 09:38:43 CST 2018
     */
    int updateByExample(@Param("record") SocketLog record, @Param("example") SocketLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_log
     *
     * @mbg.generated Fri Aug 24 09:38:43 CST 2018
     */
    int updateByPrimaryKeySelective(SocketLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_log
     *
     * @mbg.generated Fri Aug 24 09:38:43 CST 2018
     */
    int updateByPrimaryKey(SocketLog record);
}