package com.jimi.smt.eps.display.entity;

public class Line {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.id
     *
     * @mbg.generated Tue Aug 14 15:05:07 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.line
     *
     * @mbg.generated Tue Aug 14 15:05:07 CST 2018
     */
    private String line;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.id
     *
     * @return the value of line.id
     *
     * @mbg.generated Tue Aug 14 15:05:07 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.id
     *
     * @param id the value for line.id
     *
     * @mbg.generated Tue Aug 14 15:05:07 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.line
     *
     * @return the value of line.line
     *
     * @mbg.generated Tue Aug 14 15:05:07 CST 2018
     */
    public String getLine() {
        return line;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.line
     *
     * @param line the value for line.line
     *
     * @mbg.generated Tue Aug 14 15:05:07 CST 2018
     */
    public void setLine(String line) {
        this.line = line == null ? null : line.trim();
    }
}