package com.jimi.smt.eps_server.entity;

public class CenterState {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_state.line
     *
     * @mbg.generated Fri Aug 24 09:38:43 CST 2018
     */
    private String line;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_state.alarming
     *
     * @mbg.generated Fri Aug 24 09:38:43 CST 2018
     */
    private Boolean alarming;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_state.converyPaused
     *
     * @mbg.generated Fri Aug 24 09:38:43 CST 2018
     */
    private Boolean converypaused;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_state.line
     *
     * @return the value of center_state.line
     *
     * @mbg.generated Fri Aug 24 09:38:43 CST 2018
     */
    public String getLine() {
        return line;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_state.line
     *
     * @param line the value for center_state.line
     *
     * @mbg.generated Fri Aug 24 09:38:43 CST 2018
     */
    public void setLine(String line) {
        this.line = line == null ? null : line.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_state.alarming
     *
     * @return the value of center_state.alarming
     *
     * @mbg.generated Fri Aug 24 09:38:43 CST 2018
     */
    public Boolean getAlarming() {
        return alarming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_state.alarming
     *
     * @param alarming the value for center_state.alarming
     *
     * @mbg.generated Fri Aug 24 09:38:43 CST 2018
     */
    public void setAlarming(Boolean alarming) {
        this.alarming = alarming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_state.converyPaused
     *
     * @return the value of center_state.converyPaused
     *
     * @mbg.generated Fri Aug 24 09:38:43 CST 2018
     */
    public Boolean getConverypaused() {
        return converypaused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_state.converyPaused
     *
     * @param converypaused the value for center_state.converyPaused
     *
     * @mbg.generated Fri Aug 24 09:38:43 CST 2018
     */
    public void setConverypaused(Boolean converypaused) {
        this.converypaused = converypaused;
    }
}